### ISSUE TITLE
can you make it installable

### ISSUE THREAD

**Issue by MarcelH-Tabeo** [reflechant/constructor-check#6]
something like:
go install github.com/reflechant/constructor-check@latest

**Comment by reflechant** [comment]
I changed the project layout so that I have main package in the root and it's installable now

**Comment by MarcelH-Tabeo** [comment]
and that works ! (Thanks)
btw: now the instruction to run it , should probably also be changed ;-)

**Comment by reflechant** [comment]
I did change the README but yeah, it shouldn't say ./constructor-check as it should be in the $PATH after go install.
Fixed.
